// demo/vue/DemoPage.vue
<template>
  <div>
    <header>{{this.title}}</header>
    <demo-component :greeting="this.T('greeting', {name:'Kathy',age:26})" :how-are-you="this.T('howAreYou')" :img-src="this.T('imgSrc')"/>
    <button @click="setLang('en-US')"> en-US </button>
    <button @click="setLang('zh-CN')"> zh-CN </button>
  </div>
</template>

<script>
import DemoComponent from './DemoComponent.vue'

export default {
  props: {
    title: {
      type: String,
      default: 'TITLE'
    }
  },
  components: { DemoComponent }
}
</script>

// demo/react/DemoPage.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import DemoComponent from './DemoComponent.js'

class DemoPage extends Component {
  constructor(props) {
    super(props)
  }

  render() {
    return (
      <div>
        <header>{this.props.title}</header>
        <DemoComponent greeting={this.T('greeting', {name:'Kathy',age:26})} howAreYou={this.T('howAreYou')} imgSrc={this.T('imgSrc')}/>
        <button onClick={() => this.setLang('en-US')}> en-US </button>
        <button onClick={() => this.setLang('zh-CN')}> zh-CN </button>
      </div>
    )
  }
}

DemoPage.propTypes = {
  title: PropTypes.string
}

DemoPage.defaultProps = {
  title: 'TITLE'
}

export default DemoPage
